name: cascadedFCN
channels:
  - defaults
dependencies:
  - numpy
  - pandas
  - matplotlib
  - tensorflow
  #- tensorflow-gpu
  - keras=2.1.6
  - python
  - opencv
  - pillow
  - bokeh
  - scipy=1.0.0
  # - numpy=1.14.3
  # - pandas=0.23.0
  # - matplotlib=2.2.2
  # - tensorflow=1.8.0
  # - keras=2.1.6
  # - python=3.6.5
